id = 1038973210424791051
type = 'thread'
name = 'colamine3647'
parentChannelId = 1038139785660862544
archived = true
locked = false
autoArchiveDurationMinutes = 1440
memberIds = []
pinned = false
invitable = false
appliedTags = ['Modération']
ownerId = 429388533485010954
_public = true
