id = 1038259568762957946
type = 'thread'
name = 'enimaloc5587'
parentChannelId = 1038139785660862544
archived = true
locked = false
autoArchiveDurationMinutes = 1440
memberIds = []
pinned = false
invitable = false
appliedTags = ['Modération']
ownerId = 429388533485010954
_public = true
