id = 1038139412753694814
profil.name = 'test bot'
profil.icon = ''
profil.bannerUrl = ''
profil.bannerId = ''
profil.description = ''
profil.ownerId = 136200628509605888
profil.vanityCode = ''
profil.splashUrl = ''
engagement.sendMessageOnJoin = false
engagement.canWelcomedWithStickers = false
engagement.sendMessageWhenBoost = false
engagement.sendTipsAboutConfig = false
engagement.systemChannel = 0
engagement.defaultNotification = 'MENTIONS_ONLY'
engagement.afkChannel = 0
engagement.afkTimeout = 300
engagement.enabledWidget = false
engagement.defaultChannelId = 0
boost.displayBoostBar = false
boost.unlockBanner = false
boost.unlockCustomInviteUrl = false
access.serverRule = true
security.verificationLevel = 'LOW'
security.explicitContentLevel = 'ALL'
security.mfaLevel = 'NONE'
security.nsfwLevel = 'DEFAULT'
banList = []
community.enabled = true
community.rulesChannel = 1038139481338945556
community.communityUpdateChannel = 1038139481338945557
community.securityChannel = 0
community.language = 'fr'
community.description = ''
