id = 1487570126298415304
name = 'new role'
permissions.'Manage Server' = false
permissions.'Manage Webhooks' = false
permissions.'Send Messages' = true
permissions.'View Server Insights' = false
permissions.'Create Instant Invite' = true
permissions.'Pin Messages' = false
permissions.'Send Messages in Threads' = true
permissions.'Use Soundboard' = true
permissions.'View Audit Log' = false
permissions.Administrator = false
permissions.Unknown = false
permissions.'Send Voice Messages' = true
permissions.'Move Members' = false
permissions.'Manage Roles' = false
permissions.'Create Public Threads' = true
permissions.'Timeout Members' = false
permissions.'Use External Stickers' = true
permissions.'Create Polls' = true
permissions.'Use External Apps' = true
permissions.Connect = true
permissions.'Request to Speak' = true
permissions.'Create Private Threads' = true
permissions.'Manage Nicknames' = false
permissions.'Embed Links' = true
permissions.'Set Voice Channel Status' = true
permissions.'Manage Expressions' = false
permissions.Video = true
permissions.'Mute Members' = false
permissions.'Create Events' = false
permissions.'Bypass Slowmode' = false
permissions.'Priority Speaker' = false
permissions.'Change Nickname' = true
permissions.'Add Reactions' = true
permissions.'Read History' = true
permissions.'Manage Channels' = false
permissions.'Use Application Commands' = true
permissions.'Mention Everyone' = false
permissions.'Manage Events' = false
permissions.'Deafen Members' = false
permissions.'Use Voice Activity' = true
permissions.'Ban Members' = false
permissions.'Manage Messages' = false
permissions.'View Creator Analytics' = false
permissions.'Use External Emojis' = true
permissions.'View Channels' = false
permissions.'Manage Permissions' = false
permissions.'Attach Files' = true
permissions.'Manage Threads' = false
permissions.Speak = true
permissions.'Kick Members' = false
permissions.'Use External Sounds' = true
permissions.'Send TTS Messages' = false
permissions.'Use Activities' = true
permissions.'Create Expressions' = false
iconUrl = ''
primaryColor = 536870911
secondaryColor = 536870911
tertiaryColor = 536870911
mentionable = false
hoist = false
position = 16
managed = false
publicRole = false
botId = 0
isBot = false
isBoost = false
isIntegration = false
isLinkedRole = false
