id = 1053001996157857883
type = 'category'
name = 'eSportLine Bot - Temp channel'
position = 20
memberOverride.0.'Manage Server' = 0
memberOverride.0.'Manage Webhooks' = 0
memberOverride.0.'Send Messages' = 0
memberOverride.0.'View Server Insights' = 0
memberOverride.0.'Create Instant Invite' = 0
memberOverride.0.'Pin Messages' = 0
memberOverride.0.'Send Messages in Threads' = 0
memberOverride.0.'Use Soundboard' = 0
memberOverride.0.'View Audit Log' = 0
memberOverride.0.Administrator = 0
memberOverride.0.Unknown = 0
memberOverride.0.'Send Voice Messages' = 0
memberOverride.0.'Move Members' = 0
memberOverride.0.'Manage Roles' = 0
memberOverride.0.'Create Public Threads' = 0
memberOverride.0.'Timeout Members' = 0
memberOverride.0.'Use External Stickers' = 0
memberOverride.0.'Create Polls' = 0
memberOverride.0.'Use External Apps' = 0
memberOverride.0.Connect = 1
memberOverride.0.'Request to Speak' = 0
memberOverride.0.'Create Private Threads' = 0
memberOverride.0.'Manage Nicknames' = 0
memberOverride.0.'Embed Links' = 0
memberOverride.0.'Set Voice Channel Status' = 0
memberOverride.0.'Manage Expressions' = 0
memberOverride.0.Video = 0
memberOverride.0.'Mute Members' = 0
memberOverride.0.'Create Events' = 0
memberOverride.0.'Bypass Slowmode' = 0
memberOverride.0.'Priority Speaker' = 0
memberOverride.0.'Change Nickname' = 0
memberOverride.0.'Add Reactions' = 0
memberOverride.0.'Read History' = 0
memberOverride.0.'Manage Channels' = 0
memberOverride.0.'Use Application Commands' = 0
memberOverride.0.'Mention Everyone' = 0
memberOverride.0.'Manage Events' = 0
memberOverride.0.'Deafen Members' = 0
memberOverride.0.'Use Voice Activity' = 0
memberOverride.0.'Ban Members' = 0
memberOverride.0.'Manage Messages' = 0
memberOverride.0.'View Creator Analytics' = 0
memberOverride.0.'Use External Emojis' = 0
memberOverride.0.'View Channels' = 1
memberOverride.0.'Manage Permissions' = 0
memberOverride.0.'Attach Files' = 0
memberOverride.0.'Manage Threads' = 0
memberOverride.0.Speak = 0
memberOverride.0.'Kick Members' = 0
memberOverride.0.'Use External Sounds' = 0
memberOverride.0.'Send TTS Messages' = 0
memberOverride.0.'Use Activities' = 0
memberOverride.0.'Create Expressions' = 0
roleOverride = {}
