id = 1487570160113029171
type = 'text'
name = 'a'
position = 4
parentCategoryId = 1487570132778750072
positionInCategory = 0
memberOverride = {}
roleOverride = {}
topic = ''
slowmode = 0
nsfw = false
