id = 1487241975634857994
type = 'text'
name = 'a'
position = 28
parentCategoryId = 1487241956156506122
positionInCategory = 0
memberOverride = {}
roleOverride = {}
topic = ''
slowmode = 0
nsfw = false
