id = 1349506199090892894
type = 'thread'
name = 'Nouveau salon'
parentChannelId = 1349505450474999948
archived = true
locked = false
autoArchiveDurationMinutes = 10080
memberIds = []
pinned = false
invitable = false
appliedTags = ['pole discord']
ownerId = 136200628509605888
_public = true
